name: Publish

on:
  push:
    branches: ["master", "main"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - uses: valitydev/action-frontend/publish@v0.1
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
